apiVersion: apps/v1
kind: Deployment
metadata:
  name: dash-deployment
  labels:
    app: dash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dash
  template:
    metadata:
      labels:
        app: dash
    spec:
      containers:
      - name: dash
        image: ghcr.io/whattheearl/dash:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
      imagePullSecrets:
      - name: regcred
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dash-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: dash.wte.sh
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dash-service
            port:
              number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dash-service
spec:
  type: NodePort
  selector:
    app: dash
  ports:
    - port: 8080
      targetPort: 8080