FROM node:20-alpine as builder
WORKDIR /builder
COPY package*.json .
RUN npm ci
COPY . .
RUN npm run build

FROM node:20-alpine
WORKDIR /etc/dash
COPY package*.json .
RUN npm ci --omit=dev
COPY --from=builder /builder/build ./build
COPY . .
ENV PORT=8080
EXPOSE 8080
RUN export PORT=8080
CMD [ "node", "./build/index.js" ]