apiVersion: v1
kind: ConfigMap
metadata:
    name: dash-config
    namespace: default
data:
    SESSION_MAX_LENGTH: 24h
    SESSION_SECRET: ENC[AES256_GCM,data:C2CRpG7Q/f5vW2+3Yry1rrqxD6aDarPcBHoJ2+WKiIRDdFsfk8ig19VnhA==,iv:EtXK3Ds3BMyA4wApvMJXx0yP49i1wykt7C7C3XcRf+c=,tag:SN+HquF9E1IdjkDLlNoYwA==,type:str]
    # https://console.cloud.google.com/apis/credentials/oauthclient/266251998613-ct1jjtidrt1q465s14prpp9evavv5osk.apps.googleusercontent.com?project=home-402119
    OAUTH_CLIENT_ID: 266251998613-ct1jjtidrt1q465s14prpp9evavv5osk.apps.googleusercontent.com
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:yVwUwVEqrHh6jPfuwI/zFO40xzT1dncr3zyrjeB5Wwe1zXM=,iv:o+FdTju6gJx/ffwU0bnseb0lTzaOHZhIHCRpRQ12uwI=,tag:WOfiiHR6p+tKQMI4C4UsWA==,type:str]
    OAUTH_CLIENT_REDIRECT: https://dash.wte.sh/auth/callback
    OAUTH_ISSUER_URL: https://accounts.google.com
    DB: /etc/dash/sqlite.db
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15l9w7204pax6tfgcmlzplvggn67cdgu6ppry4nhns0x73n2leucq5zknjp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQclZMeER5dmd3S2lrSnVJ
            NTJQc3Znd0haU1lvTzh6UU1qa1pvbFhIOEFNCmtyVFN0WVRkbDdBaHh6bzUzbWxv
            Z3hFSjlwck5oMHZtTVh1VkdIM0NBQjAKLS0tIHBNOUd6SEhoL3FibDNkMWw3YW1O
            Q2h1OWxyNzRwT0VxUmdZTGh3ellhR1EKsH/TmmNo7Hy3GsvCTP1V1C+eRO28tYr7
            cKD8t7fz9AETJYZMmzrlTkm0wBvu2zfnwtcHL42qgHjvpDF0xaIhpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-12T23:24:54Z"
    mac: ENC[AES256_GCM,data:SfhoxFquU5rqbcrQEemmvVzT9qldqNXB+H/8yCjSFBdXN3ZFDHbfVmLhxxTeKDA+UpoTLgOU7AjcwCc//7LcgA2Hs3PpV9/IU8K5FET9/qsqwO/gReXE6tvFqTPiC302HZYQXl7EwgqijFD+yG1UE1Q+qv8cbYljO4/PypQqA0c=,iv:uNeifhrPDeC9E52ipIPxstNsmA8m8y5lHv+q0dGxZrk=,tag:jkUHkhLtMAoB1TKY+q94Qw==,type:str]
    pgp: []
    encrypted_regex: ^(.*SECRET.*)$
    version: 3.8.1
