apiVersion: apps/v1
kind: Deployment
metadata:
  name: dash-deployment
  labels:
    app: dash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dash
  template:
    metadata:
      labels:
        app: dash
    spec:
      containers:
      - name: dash
        image: ghcr.io/jonathanearl-tylertech/dash:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: dash-config
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 5
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
      imagePullSecrets:
      - name: regcred
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dash-ingress
  annotations:
    cert-manager.io/issuer: letsencrypt-staging
spec:
  rules:
  - host: dash.wte.sh
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name:  dash-service
            port:
              number: 8080
  tls:
  - hosts:
    - dash.wte.sh
    secretName: letsencrypt-staging
---
apiVersion: v1
kind: Service
metadata:
  name: dash-service
spec:
  type: NodePort
  selector:
    app: dash
  ports:
    - port: 8080
      targetPort: 8080