apiVersion: ENC[AES256_GCM,data:vEc=,iv:WG06kFSJMtnfF5+VhVoKCnYB6nHdZTmnB9k0Zx99Ad0=,tag:oB0m0KaQIbRBmPbxS6RftA==,type:str]
kind: ENC[AES256_GCM,data:UNS0Ufmr,iv:HRw0LhrFevuF783IkS5h4B+EE01nUqV1JLIcdBnknRg=,tag:TGVc7ocNEeZLhSUvexafFw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:GI+O5/+rCHxfvLk=,iv:gPspqt2NpR4iJqXnOZ+hx8QU61Xa0jjcD6K7VbKfB3s=,tag:wg4UiKAN6efPDrfvu+5RnQ==,type:str]
    namespace: ENC[AES256_GCM,data:kAxJ2TNBHA==,iv:TXEirDjAhNOgRaFfmb1myHO9FX1A0y+J9IsS/XI3oQk=,tag:RJEKwid6fdXpJrbV0QSjZw==,type:str]
type: ENC[AES256_GCM,data:mGn/hWuQ,iv:MgAc1qaKlW0M7DRk7tlCf5JzJZOpezPiBr56AfJImlk=,tag:jvMXPzTTH1DngJKyiAtKcg==,type:str]
stringData:
    dotenv: ENC[AES256_GCM,data:T4P+D62c3qC1cc5c3NuZJX1iPlrxX6XxP++loMlFQD2D0BAgZXPzmGwfbRKUNaxKNt9KN5n1DrTAMTeThkC3l2AbPfz04I6guHBE4hZ58G9YFmzU68J4HOpLmuGROAUQdygPywlPa6ATCgPqDSGdZUg7wuTo3OAxU4nZaP9No55wDcH9M2D2GEN7BQ/SmOllZ6JB4VcDX304pfPh58PWlkbMRzG2o0B1m0Zf,iv:V7lE+lmZvqjQMY3RWJx63OK3nvtQUX5/0b1reY6cshg=,tag:EZAbSxfSDBrZ//0LydKhAA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15l9w7204pax6tfgcmlzplvggn67cdgu6ppry4nhns0x73n2leucq5zknjp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJOC9SUlVONzI5Z2trSitQ
            TzRyZGpNdTN1RFg2Nm4xOU5QVFRrOU5PRDJzCjBGV3B3TWloNEZhSzdnL3M3UGZa
            REtwL0g0RWtvT21DL29ySUZESm50cjAKLS0tIGp0TTF5aGZKV01oK29LdHZYM2tz
            V2RoVTRJTG9yanpUZFlBTDU4SllnNGMKKqFyX1tuwQ3+0Kgxbn7kXsJoUsqDlxv9
            gVtNKWq4Xwji/NWyiQBztioFNYmBQxayZ64v62SGQQu5ACUqVqxVZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-09T07:19:01Z"
    mac: ENC[AES256_GCM,data:jUtjljWYqQerRjXrMHIi800YUZAtxkddHOVt+X/8F/zdnDbNNhipjJ4O+LdndJjPA70ojnAgsGejk57qa8UsiBtvjYDx3E7ErrIgchspfJp+gHQAhbSEPJUILTN1wFLS8k5E1tQge/mm6lU24yj4k8yYd78C+9+Rxiky0BgGTJw=,iv:G1NZY9ChLK8sjTsXKTE3Q1A2v6kTu8CMcZGr5NB7KPY=,tag:SINLg/3yCTKSfOrrHegtmw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
